import {
  DEFAULT_CSP_VALUES,
  type TCspSource,
  type TCspValuesType
} from './contentSecurityPolicy.Type'

/** Function mergeCSPValues - Merge to CSP objects
 * It should merge all the keys ie directive of CSP object
 * If two directives has same values then it should remove duplicate and maintain order
 * If Both directives has different values then it will do concat operation
 * @param - multiple CSP object
 * @return - merged CSP Map object
 */
export const mergeCSPValues = (
  ...cspValues: TCspValuesType[]
): Map<keyof TCspValuesType, Set<TCspSource>> => {
  if (cspValues.length === 0) {
    return new Map() as Map<keyof TCspValuesType, Set<TCspSource>>
  }

  let mergedObj: Map<keyof TCspValuesType, Set<TCspSource>> = new Map()

  for (const cspValue of cspValues) {
    for (const key in cspValue) {
      const index = key as keyof TCspValuesType
      const defaultValuesIndex = mergedObj.get(index)
      if (defaultValuesIndex) {
        mergedObj.set(
          index,
          new Set([...defaultValuesIndex, ...(cspValue[index] || [])])
        )
      } else {
        mergedObj.set(index, new Set(cspValue[index] || []))
      }
    }
  }

  return mergedObj
}

/** Function getCSPHeader - Get complete CSP headers in text format
 * This funcation merged SRI values with existing CSP object and
 * @param param 1 - SRI SHA values generated by Rsbuild in array format for script
 * @param param 2 - SRI SHA values generated by Rsbuild in array format for link
 * @param param 3 - Default CSP object
 * @param param 4 - Static nonce value
 * @returns CSP object of type string with merged of input value
 */
export const getCSPHeader = ({
  cspValues,
  linkNonceValue = '',
  scriptsIntegrity,
  linksIntegrity
}: {
  cspValues: TCspValuesType
  linkNonceValue: string
  scriptsIntegrity: TCspSource[]
  linksIntegrity: TCspSource[]
}) => {
  let mergedCspValues: Map<keyof TCspValuesType, Set<TCspSource>> = new Map()
  // Merge default CSP values with integrity and nonce value
  if (
    (scriptsIntegrity && scriptsIntegrity.length) ||
    (linksIntegrity && linksIntegrity.length)
  ) {
    // if nonce is disabled then don't add
    const integrityCspValues: TCspValuesType = {
      'script-src': [...scriptsIntegrity],
      'style-src': [...linksIntegrity]
    }
    const nonceVal = linkNonceValue.length ? `'nonce-${linkNonceValue}'` : ''
    if (nonceVal) {
      integrityCspValues['style-src']?.push(nonceVal as TCspSource)
    }

    mergedCspValues = mergeCSPValues(
      DEFAULT_CSP_VALUES,
      cspValues,
      integrityCspValues
    )
  }

  let cspString = ''
  mergedCspValues.forEach((value, key) => {
    const cspValue = Array.from(value).join(' ')
    if (cspValue.length === 0) {
      return
    }

    cspString += `${key} ${Array.from(value).join(' ')}; `
  })

  // Explicity handling for some directives
  const mediaSrc = mergedCspValues.get('media-src')
  if (!mediaSrc || mediaSrc.size === 0) {
    cspString += `media-src 'none'; `
  }

  // Explicity handling for some directives
  const objectSrc = mergedCspValues.get('object-src')
  if (!objectSrc || objectSrc.size === 0) {
    cspString += `object-src 'none'; `
  }

  // Explicity handling for some directives
  // const frameSrc = mergedCspValues.get('frame-src')
  // if (!frameSrc || frameSrc.size === 0) {
  //   cspString += `frame-src 'none'; `
  // }

  return cspString
}
