import {
  DEFAULT_CSP_VALUES,
  HANDLE_EMPTY_CASES,
  type TCspSource,
  type TCspValuesType
} from './contentSecurityPolicy.Type'

const handleEmptyCase = (
  cspString: string,
  mergedCspValues: Map<keyof TCspValuesType, Set<TCspSource>>,
  dir: keyof TCspValuesType
): string => {
  const directive = mergedCspValues.get(dir)
  if (!directive || directive.size === 0) {
    cspString += `${dir} 'none'; `
  }
  return cspString
}

/** Function mergeCSPValues - Merge to CSP objects
 * It should merge all the keys ie directive of CSP object
 * If two directives has same values then it should remove duplicate and maintain order
 * If Both directives has different values then it will do concat operation
 * @param - multiple CSP object
 * @return - merged CSP Map object
 */
export const mergeCSPValues = (
  ...cspValues: TCspValuesType[]
): Map<keyof TCspValuesType, Set<TCspSource>> => {
  if (cspValues.length === 0) {
    return new Map() as Map<keyof TCspValuesType, Set<TCspSource>>
  }

  let mergedObj: Map<keyof TCspValuesType, Set<TCspSource>> = new Map()

  for (const cspValue of cspValues) {
    for (const key in cspValue) {
      const index = key as keyof TCspValuesType
      const defaultValuesIndex = mergedObj.get(index)
      if (defaultValuesIndex) {
        mergedObj.set(
          index,
          new Set([...defaultValuesIndex, ...(cspValue[index] || [])])
        )
      } else {
        mergedObj.set(index, new Set(cspValue[index] || []))
      }
    }
  }

  return mergedObj
}

/** Function getCSPHeader - Get complete CSP headers in text format
 * This funcation merged SRI values with existing CSP object and
 * @param param 1 - SRI SHA values generated by Rsbuild in array format for script
 * @param param 2 - SRI SHA values generated by Rsbuild in array format for link
 * @param param 3 - Default CSP object
 * @param param 4 - Static nonce value
 * @returns CSP object of type string with merged of input value
 */
export const getCSPHeader = ({
  cspValues,
  linkNonceValue = '',
  scriptsIntegrity,
  linksIntegrity
}: {
  cspValues: TCspValuesType
  linkNonceValue: string
  scriptsIntegrity: TCspSource[]
  linksIntegrity: TCspSource[]
}) => {
  let mergedCspValues: Map<keyof TCspValuesType, Set<TCspSource>> = new Map()

  let integrityCspValues: TCspValuesType = {}

  // Merge default CSP values with integrity and nonce value
  if (
    (scriptsIntegrity && scriptsIntegrity.length) ||
    (linksIntegrity && linksIntegrity.length)
  ) {
    // if nonce is disabled then don't add
    integrityCspValues = {
      'script-src': [...scriptsIntegrity],
      'style-src': [...linksIntegrity]
    }
  }

  if (linkNonceValue) {
    const nonceVal = `'nonce-${linkNonceValue}'`
    integrityCspValues['style-src']?.push(nonceVal as TCspSource)
  }

  mergedCspValues = mergeCSPValues(
    DEFAULT_CSP_VALUES,
    cspValues,
    integrityCspValues
  )

  let cspString = ''
  mergedCspValues.forEach((value, key) => {
    const cspValue = Array.from(value).join(' ')
    if (cspValue.length === 0) {
      return
    }

    cspString += `${key} ${Array.from(value).join(' ')}; `
  })

  // handle empty cases set none
  HANDLE_EMPTY_CASES.forEach(dir => {
    cspString = handleEmptyCase(
      cspString,
      mergedCspValues,
      dir as keyof TCspValuesType
    )
  })

  return cspString
}
